### ISSUE TITLE
Blank screen shown when fullscreen button is clicked

### ISSUE THREAD

**Issue by Sahana312** [cprcrack/VideoEnabledWebView#28]
When the full screen button is clicked a blank black screen is shown sometimes. The video doesnt appear only the audio will be playing in the background. This happens even in your demo. i am loading an iframe with loadHtml(). Is there anything extra I have to do?

**Comment by Myerden** [comment]
could you show your code and layout file to see what is happening?

**Comment by igorfastronicorrea** [comment]
Hi guyz,

do you have any idea how fix this?

**Comment by FrankNT** [comment]
Same issue, could anyone help us?

**Comment by Myerden** [comment]
I have faced like these problems. I fixed this by importing this views into my project directly.
I copied all the views and components into my project, created required classes then used that views. And now I can play youtube videos without having problem.

[webview.zip](https://github.com/cprcrack/VideoEnabledWebView/files/1360515/webview.zip)

this zip archive includes the same VideoEnabledWebView.java and VideoEnabledWebChromeClient.java

You can copy these to your project and then use it.

thank you @cprcrack :+1:

**Comment by HardikMaru** [comment]
@Myerden  I have replaced the files with your one, still the same issue. Only white blank screen.

**Comment by igorfastronicorrea** [comment]
Hi Guy, My suggestion is utilized Google Youtube v3

https://developers.google.com/youtube/v3/

**Comment by BigCoach** [comment]
Try to replace .setVisibility(View.INVISIBLE ); with .setVisibility(View.GONE); in VideoEnabledWebChromeClient
It helped me
